# Generated by Django 3.2.3 on 2021-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0004_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default='user_adress', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(default='user_city', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='state',
            field=models.CharField(default='user_state', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='zip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
