# Generated by Django 3.2.3 on 2021-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0007_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='k', max_length=255),
        ),
    ]
