# Generated by Django 3.2.3 on 2021-05-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.CharField(default='k', max_length=2000),
        ),
    ]
