# Generated by Django 3.2.3 on 2021-05-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0011_alter_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
    ]
