# Generated by Django 3.2.3 on 2021-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0012_remove_product_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.CharField(default='h', max_length=2000),
        ),
    ]
