# Generated by Django 3.2.3 on 2021-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0013_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.CharField(max_length=2000),
        ),
    ]
