# Generated by Django 3.2.3 on 2021-05-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0015_remove_saled_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saled',
        ),
    ]
