# Generated by Django 3.2.3 on 2021-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0017_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
